version: '2'
services:
services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.customelement.dev
    command: polymer serve -H 0.0.0.0
    ports:
      - "8081:8081"
  customelement:
    build:
      context: .
      dockerfile: docker/Dockerfile.customelement
    ports:
      - "8080:8080"
  contracts:
    build:
      context: .
      dockerfile: docker/Dockerfile.contracts
  lint:
    build:
      context: .
      dockerfile: docker/Dockerfile.lint
