FROM node:7.10-wheezy
RUN npm install -g polymer-cli
RUN npm install -g bower
RUN npm install -g pm2

RUN mkdir /app
WORKDIR /app

COPY browserify.js ./
COPY wct.conf.json ./
COPY manifest.json ./
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY bower.json ./
RUN bower install --allow-root

COPY truffle.js ./
COPY ethpm.json ./

RUN npm run getcontractlibs

RUN mkdir -p contracts/ && cp -R installed_contracts/swarmcity/ contracts/swarmcity/
RUN mkdir -p contracts/zeppelin/contracts/ownership/ && \
    cp installed_contracts/zeppelin/contracts/ownership/Ownable.sol \
           contracts/zeppelin/contracts/ownership/Ownable.sol

# hack to allow importing swarmcity:0.0.1
RUN mkdir -p contracts/swarmcity/installed_contracts/zeppelin/contracts/ownership/ && \
    cp installed_contracts/zeppelin/contracts/ownership/Ownable.sol \
           contracts/swarmcity/installed_contracts/zeppelin/contracts/ownership/Ownable.sol

COPY contracts ./contracts/

RUN npm run compilecontracts
RUN npm run copy

COPY index.html ./
COPY images ./images/
COPY src ./src/

COPY polymer.json ./

EXPOSE 8081

CMD polymer serve -H 0.0.0.0
