FROM node:7.10-wheezy
RUN npm install -g polymer-cli
RUN npm install -g bower
RUN npm install -g pm2

RUN mkdir /app
WORKDIR /app

COPY browserify.js ./
COPY wct.conf.json ./
COPY manifest.json ./
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY bower.json ./
RUN bower install --allow-root

#COPY truffle.js ./
#COPY ethpm.json ./
#
#RUN npm run getcontractlibs
#
#RUN mkdir -p contracts/ && cp -R installed_contracts/swarmcity/ contracts/swarmcity/
#RUN mkdir -p contracts/zeppelin/contracts/ownership/ && \
#    cp installed_contracts/zeppelin/contracts/ownership/Ownable.sol \
#           contracts/zeppelin/contracts/ownership/Ownable.sol
#
## hack to allow importing swarmcity:0.0.1
#RUN mkdir -p contracts/swarmcity/installed_contracts/zeppelin/contracts/ownership/ && \
#    cp installed_contracts/zeppelin/contracts/ownership/Ownable.sol \
#           contracts/swarmcity/installed_contracts/zeppelin/contracts/ownership/Ownable.sol
#
#COPY contracts ./contracts/
#
#RUN npm run compilecontracts
#RUN npm run copy


COPY index.html ./
COPY images ./images/
COPY src ./src/

COPY service-worker.js ./
COPY sw-precache-config.js ./

COPY service-worker.js ./


COPY polymer.json ./

# RUN npm run browserify
RUN polymer build

#RUN cp src/redux-state.html build/es6-unbundled/src/
#RUN cp src/shared-styles.html build/es6-unbundled/src/

#RUN npm run copyjs
#RUN cp src/swarm-city.min.js build/es5-bundled/src && \
#    cp src/swarm-city.min.js build/es6-bundled/src/ && \
#    cp src/swarm-city.min.js build/es6-unbundled/src/


#RUN ln -s src/swarm-city.min.js build/es5-bundled/src/swarm-city.min.js && \
#    ln -s src/swarm-city.min.js build/es6-bundled/src/swarm-city.min.js && \
#    ln -s src/swarm-city.min.js build/es6-unbundled/src/swarm-city.min.js
#
#RUN ln -s bower_components/polymer/ build/es5-bundled/bower_components/polymer && \
#    ln -s bower_components/polymer/ build/es6-bundled/bower_components/polymer && \
#    ln -s bower_components/polymer/ build/es6-unbundled/bower_components/polymer && \
#
#RUN ln -s bower_components/app-route/ build/es5-bundled/bower_components/app-route && \
#    ln -s bower_components/app-route/ build/es6-bundled/bower_components/app-route && \
#    ln -s bower_components/app-route/ build/es6-unbundled/bower_components/app-route && \
#
#RUN ln -s bower_components/neon-animation/ build/es5-bundled/bower_components/neon-animation && \
#    ln -s bower_components/neon-animation/ build/es6-bundled/bower_components/neon-animation && \
#    ln -s bower_components/neon-animation/ build/es6-unbundled/bower_components/neon-animation && \

#RUN cp src/redux-state.html build/es5-bundled/src/ && \

#RUN cp src/redux-state.html build/es5-bundled/src/ && \
#    cp src/redux-state.html build/es6-bundled/src/ && \
#
#RUN cp src/shared-styles.html build/es5-bundled/src/ && \
#    cp src/shared-styles.html build/es6-bundled/src/ && \

COPY pm2.json ./
COPY server.js ./

EXPOSE 8080

CMD [ "pm2-docker", "start", "pm2.json" ]
